{{- if .Values.cron_job }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- with $.Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.cron_job.schedule }}
  successfulJobsHistoryLimit: {{ .Values.cron_job.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.cron_job.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
            app.kubernetes.io/instance: {{ $.Release.Name | quote }}
            helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
            {{- with $.Values.app.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "app.serviceAccountName" . }}
          {{- with .Values.cron_job.containers }}
          containers:
            {{ . | toYaml | nindent 10}}
          {{- end }}
          {{- if .Values.cron_job.volumes }}
          {{- with .Values.cron_job.volumes }}
          volumes:
            {{ . | toYaml | nindent 10}}
          {{- end }}
          {{- end }}

{{- end }}
