{{- if .Values.externalSecretsSecretsManager }}

apiVersion: "external-secrets.io/v1beta1"
kind: "ExternalSecret"
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.externalSecretsExtra.namespace }}
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecretsExtra.secretStoreKind }}
    name: {{ .Values.externalSecretsExtra.secretStoreName }}
  target:
    name: {{ .Values.externalSecretsExtra.target }}
    {{- if .Values.externalSecretsExtra.template }}
    {{- with .Values.externalSecretsExtra.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- with .Values.externalSecretsExtra.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}

{{- with .Values.ssmExternalSecrets }}

{{- end }}