{{- with .Values.migration }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name | quote}}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- with $.Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ $.Release.Name }}"
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
     {{- end }}
      labels:
        app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
        helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
        {{- with $.Values.app.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .name | quote }}
        image: {{ .image | default $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
        command: {{ toYaml .command | nindent 10 }}
            {{- with $.Values.env }}
        env:
            {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- if .env }}
            {{- toYaml .env | nindent 10 }}
            {{- end }}
{{- end }}
