{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | quote }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | quote }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}