{{- if .Values.volumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeClaim.name }}
spec:
  accessModes: 
    - {{ .Values.volumeClaim.accessMode }}
  storageClassName: {{ .Values.volumeClaim.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeClaim.size }}
{{- end }}
