{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end}}
---
{{- if .Values.multiService }}
{{- range .Values.multiService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name  }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with $.Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .type }}
  ports:
    - name: {{ .name  }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
    {{- with $.Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end}}
{{- end}}
