app:
  environment: "sandbox"
  replicaCount: 1

  image:
    repository: 973672886160.dkr.ecr.eu-west-1.amazonaws.com/checkout-sandbox
    pullPolicy: Always
    tag: 7

  containers:
    ports:
      port: 3000
      proto: TCP

  livenessProbe:
    enabled: true
    port: 3000
    path: "/"
    initialDelaySeconds: 15
    periodSeconds: 5

  readinessProbe:
    enabled: true
    port: 3000
    path: "/"
    initialDelaySeconds: 15
    periodSeconds: 5

  imagePullSecrets:
    - name: dockerhub

  nameOverride: "nikas-sandbox-checkout"

  fullnameOverride: "nikas-sandbox-checkout"

  serviceAccount:
    create: yes
    annotations: {}
    name: "nikas-sandbox-checkout"

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  service:
    type: NodePort
    port: 80
    targetPort: 3000

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer
    hosts:
      - host: sandbox-checkout.anikipay.com
        paths:
        - path: /
          backend:
            service:
              name: "nikas-sandbox-checkout"
              port:
                number: 80
    tls:
     - secretName: nikas-sandbox-checkout-cert-secret
       hosts:
         - sandbox-checkout.anikipay.com
    ingressClassName: nginx-nonprod

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  autoscaling: {}
  #   enabled: true
  #   minReplicas: 1
  #   maxReplicas: 10
  #   targetCPUUtilizationPercentage: 85
  #   targetMemoryUtilizationPercentage: 80

  nodeSelector:
      Environment: "qa"

  tolerations: []

  affinity: {}

  app:
    labels:
      app: nikas-sandbox-checkout
  env:
    - name: apiUrl
      value: "https://sandbox-api.anikipay.com"
    - name: port
      value: "3000"
    - name: apiKey
      valueFrom:
        secretKeyRef:
          name: nikas-sandbox-checkout
          key: apiKey

  externalSecrets:
    namespace: "nikas-sandbox"
    secretStoreKind: "SecretStore"
    secretStoreName: "sandbox-secret-store"
    target: nikas-sandbox-checkout
    data:
      - remoteRef:
          key: /nikas/sandbox/checkout/apiKey
        secretKey: apiKey

  # externalServices:
  #   services:
  #     - name: postgre
  #       externalName: eks-test.ctdmvlscllk3.eu-west-1.rds.amazonaws.com
  #     - name: redis
  #       externalName: eks-test.bq7fff.ng.0001.euw1.cache.amazonaws.com
