{{- with .Values.migration }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name | quote}}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ $.Release.Name }}"
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .name | quote }}
        image: {{ .image | default $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
        command: {{ toYaml .command | nindent 10 }}
            {{- with $.Values.env }}
        env:
            {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- if .env }}
            {{- toYaml .env | nindent 10 }}
            {{- end }}
{{- end }}
