{{- if .Values.externalSecrets }}

apiVersion: "external-secrets.io/v1beta1"
kind: "ExternalSecret"
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.externalSecrets.namespace }}
spec:
  target: 
    name: {{ include "app.fullname" . }}
  secretStoreRef: 
    kind: {{ .Values.externalSecrets.secretStoreKind }}
    name: {{ .Values.externalSecrets.secretStoreName }}
  {{- with .Values.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}


