apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
spec:
  backendType: {{ .Values.externalSecrets.backendType }}
  region: {{ .Values.externalSecrets.region }}
  {{- with .Values.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
