name: Push to Chartmusem
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Install Helm cm-push plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push.git
      - name: Push helm chart to Devops Helm Chart repository
        run: |
          for i in $(ls -d */)
          do    
            helm cm-push -f -u ${{ secrets.CHARTMUSEUM_USER }} -p ${{ secrets.CHARTMUSEUM_PASSWORD }} $i/ http://chartmuseum.blor.me/devops/base
          done
