name: Push to Chartmusem
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/helm-push-action@v2
    env:
      SOURCE_DIR: '.'
      CHART_FOLDER: 'app'
      FORCE: 'True'
      CHARTMUSEUM_URL: 'http://chartmuseum.theguardianbank.com/devops/base'
      CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
      CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
